export { default as UserManagement } from './pages/UserManagement';
export { default as CreatorManagement } from './pages/CreatorManagement';
export { default as CreatorDetailPage } from './pages/CreatorDetailPage';
export { default as SingerManagement } from './pages/SingerManagement';
export { default as SongManagementAdmin } from './pages/SongManagementAdmin';
export { default as CreateSongAdmin } from './pages/CreateSongAdmin';
export { default as EditSongAdmin } from './pages/EditSongAdmin';
export { default as SubmissionManagement } from './pages/SubmissionManagement';
export { default as TagManagement } from './pages/TagManagement';